# Generated by Django 5.0.3 on 2024-03-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffandpatient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('appointment_history', models.TextField(blank=True, null=True)),
                ('billing_info', models.TextField(blank=True, null=True)),
                ('insurance_info', models.TextField(blank=True, null=True)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffandpatient.patient')),
            ],
        ),
    ]
