# Generated by Django 5.0.3 on 2024-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytrack',
            name='low_inventory_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
