# Generated by Django 5.0.3 on 2024-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffandpatient', '0002_appointmentrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
