# Generated by Django 5.0.3 on 2024-03-10 04:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffandpatient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffandpatient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Consultation', 'Consultation'), ('X-Ray', 'X-Ray'), ('Blood Test', 'Blood Test'), ('Admit', 'Admit'), ('Medications', 'Medications')], max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.invoice')),
            ],
        ),
    ]
