# Generated by Django 5.0.3 on 2024-03-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounting.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
