# Generated by Django 5.0.3 on 2024-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_remove_service_invoice_invoice_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_name',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('X-Ray', 'X-Ray'), ('Blood Test', 'Blood Test'), ('Admit', 'Admit'), ('Medications', 'Medications')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
